# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WBueg1YUO9cZAZSmFBH7BuE-8qWC1HZo
"""

import numpy as np
def calc(a,b,c):
  if c == "+":
    return (a+b)
  elif c == "-":
    return (a-b)
  elif c == "*":
    return (a*b)
  elif c == "/":
    return (a/b)
  elif c == ">":
    return (a>b)
  elif c == "<":
    return (a<b)
  elif c == "%":
    return (a%b)
  elif c == "**":
    return (a**b)
  elif c == "//":
    return (a//b)
  elif c == "sqrt" and b == 1:    #square root is represent by sqrt
    return (np.sqrt(a)*b)     
  else:
    return ("error")      
    
calc (6,1,"sqrt")
